apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      # when should a container restart
      livenessProbe:
        httpGet:
          # check index.html on port 80
          path: /index.html
          port: 80
        # wait 15 seconds
        initialDelaySeconds: 15
        timeoutSeconds: 2
        # check every 5 seconds
        periodSeconds: 5
        # allow one failure before failing pod
        failureThreshold: 1
      # when should a container start receiving traffic
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 5
      ports:
        - containerPort: 80
# kubectl create -f nginx.pod.yml --save-config
# kubectl describe pod my-nginx
# kubectl apply -f nginx.pod.yml
# kubectl exec my-nginx -it sh
# kubectl edit -f nginx.pod.yml
# kubectl delete -f nginx.pod.yml
